# Application properties that need to be
# embedded within the web application can be included here
server:
    port: 8443
    ssl:
        key-store: classpath:/etc/cas/thekeystore
        key-store-password: changeit
springdoc: 
    api-docs: 
        enabled: "true"
    swagger-ui:
        enabled: "true"
spring:
    main:
        allow-bean-definition-overriding: true
cas:
    audit:
        engine:
            excluded-actions: AUTHENTICATION_EVENT_TRIGGERED
        jdbc:
            driverClass: com.mysql.cj.jdbc.Driver
            dialect: org.hibernate.dialect.MySQLDialect
            user: root
            password: root
            url: jdbc:mysql://127.0.0.1:3306/sso_production?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            ddlAuto: update
            idle-timeout: PT10M
            pool: 
                max-size: "18"
                max-wait: PT60S
                timeout-millis: 10000
                maximum-lifetime: PT10M
    logging:
        mdc-enabled: "true"
    standalone: 
        configuration-security: 
            alg: PBEWithMD5AndTripleDES
            initialization-vector: true
            provider:
            psw: JimatHosting
    rest: 
        services: 
            attribute-name: "authorities"
            attribute-value: "ROLE_SERVICE_ADMIN"
    service-registry:
        jpa: 
            enabled: true
            driverClass: com.mysql.cj.jdbc.Driver
            user: root
            password: root
            url: jdbc:mysql://127.0.0.1:3306/sso_production?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC 
            dialect: org.hibernate.dialect.MySQLDialect
            ddlAuto: update
            idle-timeout: PT10M
            pool: 
                max-size: "18"
                max-wait: PT60S
                timeout-millis: 10000
                maximum-lifetime: PT10M
    ticket:
        st:
            max-length: 50
            time-to-kill-in-seconds: PT2H
        tgt:
            core:
                max-length: 50
                only-track-most-recent-session: true
            primary:
                time-to-kill-in-seconds: PT2H
                max-time-to-live-in-seconds: PT8H
        registry:
            jpa: 
                enabled: true
                driverClass: com.mysql.cj.jdbc.Driver
                user: root
                password: root
                url: jdbc:mysql://127.0.0.1:3306/sso_production?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC 
                dialect: org.hibernate.dialect.MySQLDialect
                ddlAuto: update
                idle-timeout: PT10M
                pool: 
                    max-size: "18"
                    max-wait: PT60S
                    timeout-millis: 10000
                    maximum-lifetime: PT10M
                crypto: 
                    enabled: false
            cleaner: 
               schedule: 
                   enabled-on-host: ".*"
                   enabled: true
                   repeat-interval: PT2M
                   start-delay: PT15S
            core: 
                enable-locking: false
    tgc: 
        crypto: 
            enabled: false
    authn:
        accept:
            enabled: false
        attributeRepository:
            stub:
                attributes:
                    authorities: ROLE_SERVICE_ADMIN
        token:
            crypto: 
                encryption: 
                    key: h5-MvfCYVNH48a4gKm6pujXNp4K0lssHUlTaX6xjj_0
                signing:
                    key: CN5dCk3HfFOqb4TWYso9fJ3mNKoTeBILo_e9GpI-Pe8IMyzx_dz6SjYqsNZJDmU6vPpAa5qFKef6tQ0zEGGe7A
        jdbc:
            query[0]:
                sql: SELECT * FROM auth_user WHERE email = ?
                url: jdbc:mysql://127.0.0.1:3306/sso_production?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
                dialect: org.hibernate.dialect.MySQLDialect
                user: root
                password: root
                ddlAuto: none
                driverClass: com.mysql.cj.jdbc.Driver
                fieldPassword: password
                idle-timeout: PT10M
                pool: 
                    max-size: "18"
                    max-wait: PT60S
                    timeout-millis: 10000
                    maximum-lifetime: PT10M
                passwordEncoder:
                    type: BCRYPT
                    encodingAlgorithm: PBKDF2WithHmacSHA1
    webflow:
        session:
            storage: false
        crypto: 
            enabled: false
    events:
        core: 
            enabled: true
            trackGeolocation: true
        jpa: 
            url: jdbc:mysql://127.0.0.1:3306/sso_production?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            driverClass: com.mysql.cj.jdbc.Driver
            enabled: true
            user: root
            password: root
            dialect: org.hibernate.dialect.MySQLDialect
            ddlAuto: update
            idle-timeout: PT10M
            pool: 
                max-size: "18"
                max-wait: PT60S
                timeout-millis: 10000
                maximum-lifetime: PT10M
    jdbc: 
        gen-ddl: true
        show-sql: true