# Application properties that need to be
# embedded within the web application can be included here
server:
    tomcat:
        background-processor-delay: 0s
        threads:
          max: 200  # Maximum number of worker threads
          min-spare: 10  # Minimum number of worker threads always kept alive
        max-connections: 10000  # Maximum number of connections that the server will accept and process at any given time
        accept-count: 100  # Maximum queue length for incoming connection requests when all possible request processing threads are in use
        max-keep-alive-requests: 1  # Maximum number of HTTP requests which can be pipelined until the connection is closed by the server
        connection-timeout: 20000  # Connection timeout in milliseconds
        max-http-form-post-size: 2MB  # Maximum size of the HTTP post content
        uri-encoding: UTF-8  # Character encoding to use to decode the URI
        compression:
            enabled: true  # Enable response compression
            min-response-size: 2048
    port: 8443
    ssl:
        key-store: classpath:/etc/cas/thekeystore
        key-store-password: changeit
springdoc: 
    api-docs: 
        enabled: "true"
    swagger-ui:
        enabled: "true"
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.web.embedded.EmbeddedWebServerFactoryCustomizerAutoConfiguration
    mvc:
        async:
            request-timeout: 3600000
    main:
        allow-bean-definition-overriding: true
logging:
    level:
        org.springframework.boot.autoconfigure: DEBUG
        org.apereo.cas: DEBUG
CasFeatureModule:
    Tokens:
        enabled: false
cas:
    view: 
        template-prefixes: classpath:/templates
    http-web-request:
        cors:
            enabled: false
        header:
            enabled: true
    sso: 
        create-sso-cookie-on-renew-authn: true
        sso-enabled: true
    slo: 
        asynchronous: true
        disabled: false
        logout-propagation-type: AJAX
    logout:
        follow-service-redirects: true
    audit:
        engine:
            excluded-actions: AUTHENTICATION_EVENT_TRIGGERED
        jdbc:
            driverClass: com.mysql.cj.jdbc.Driver
            dialect: org.hibernate.dialect.MySQLDialect
            user: lssdev_staging
            password: hnzIyt67X4
            url: jdbc:mysql://lssdev.info:3306/lssdev_staging?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            ddlAuto: update
    standalone: 
        configuration-security: 
            alg: PBEWithMD5AndTripleDES
            initialization-vector: true
            provider:
            psw: JimatHosting
    rest: 
        services: 
            attribute-name: "authorities"
            attribute-value: "ROLE_SERVICE_ADMIN"
    service-registry:
        jpa: 
            enabled: true
            driverClass: com.mysql.cj.jdbc.Driver
            user: lssdev_staging
            password: hnzIyt67X4
            url: jdbc:mysql://lssdev.info:3306/lssdev_staging?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC 
            dialect: org.hibernate.dialect.MySQLDialect
            ddlAuto: update
    ticket:
        st:
            max-length: 50
            time-to-kill-in-seconds: PT2H
        tgt:
            core:
                max-length: 50
                only-track-most-recent-session: true
            primary:
                time-to-kill-in-seconds: PT2H
                max-time-to-live-in-seconds: PT8H
        registry:
            jpa: 
                enabled: true
                driverClass: com.mysql.cj.jdbc.Driver
                user: lssdev_staging
                password: hnzIyt67X4
                url: jdbc:mysql://lssdev.info:3306/lssdev_staging?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC 
                dialect: org.hibernate.dialect.MySQLDialect
                ddlAuto: update
                crypto: 
                    enabled: false
            cleaner: 
               schedule: 
                   enabled-on-host: ".*"
                   enabled: true
                   repeat-interval: PT2M
                   start-delay: PT15S
            core: 
                enable-locking: false
    tgc: 
        crypto: 
            enabled: false
    authn:
        accept:
            enabled: false
        attributeRepository:
            json[0]:
                location: classpath:/etc/cas/config/user-attributes.json
        token:
            crypto: 
                encryption: 
                    key: h5-MvfCYVNH48a4gKm6pujXNp4K0lssHUlTaX6xjj_0
                signing:
                    key: CN5dCk3HfFOqb4TWYso9fJ3mNKoTeBILo_e9GpI-Pe8IMyzx_dz6SjYqsNZJDmU6vPpAa5qFKef6tQ0zEGGe7A
        jdbc:
            query[0]:
                sql: SELECT au.email as username,au.* FROM auth_user au WHERE au.email = ? AND au.inceif_status IN ('active') ORDER BY au.id DESC LIMIT 1
                url: jdbc:mysql://lssdev.info:3306/lssdev_staging?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
                dialect: org.hibernate.dialect.MySQLDialect
                user: lssdev_staging
                password: hnzIyt67X4
                ddlAuto: none
                driverClass: com.mysql.cj.jdbc.Driver
                fieldPassword: password
                principal-attribute-list: id,first_name,last_name,email,username,inceif_type,inceif_status
                passwordEncoder:
                    type: BCRYPT
                    encodingAlgorithm: PBKDF2WithHmacSHA512
    webflow:
        session:
            storage: false
        crypto: 
            enabled: false
    events:
        core: 
            enabled: true
            trackGeolocation: true
        jpa: 
            url: jdbc:mysql://lssdev.info:3306/lssdev_staging?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            driverClass: com.mysql.cj.jdbc.Driver
            enabled: true
            user: lssdev_staging
            password: hnzIyt67X4
            dialect: org.hibernate.dialect.MySQLDialect
            ddlAuto: update
    jdbc: 
        gen-ddl: true
        show-sql: true